# pytorch_lightning==1.9.5
# seed_everything: true
trainer:
  devices:
  - 0
  max_epochs: 200
  min_epochs: 30
  accelerator: gpu
  precision: 16
  accumulate_grad_batches: 3
  auto_lr_find: false
  profiler: null

  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
<<<<<<< HEAD
      save_dir: 'ckpt_3d/exp20_mask_red_182_182'
      name: 'event_detect_add_table'
=======
      save_dir: 'ckpt_3d/exp3_crop_320_400_resize_182_182_yolo_ball'
      name: ''
>>>>>>> 7fd1f88b4441a7f09042f083ac38c4004f7835c1
      version: ''
      project: 'event_detect'

  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        dirpath: ${trainer.logger.init_args.save_dir}
        filename: '{epoch}-{train_loss:.3f}-{val_loss:.3f}-{train_acc:.3f}-{train_relaxed_acc:.3f}-{val_acc:.3f}-{val_relaxed_acc:.3f}-{val_pce:.3f}-{val_smooth_pce:.3f}'
        monitor: val_loss
        save_top_k: 5
        mode: min
        every_n_epochs: 1
        auto_insert_metric_name: true

    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: ${trainer.callbacks[0].init_args.monitor}
        patience: 20
        mode: ${trainer.callbacks[0].init_args.mode}

    - class_path: RichProgressBar
      init_args:
        leave: true

    - class_path: LearningRateMonitor
      init_args:
        logging_interval: step
    
    - class_path: RichModelSummary
      init_args:
        max_depth: 1

  overfit_batches: 0.0
  fast_dev_run: false
  log_every_n_steps: 3
  check_val_every_n_epoch: 1
  auto_scale_batch_size: false
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null

  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_processes: null
  track_grad_norm: -1
  val_check_interval: null
  num_sanity_val_steps: 2
  benchmark: null
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  detect_anomaly: false
  plugins: null
  amp_backend: null
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  inference_mode: true

 
model:
  version: x3d_xs
  n_classes: 3
  class_weight:
  - 1. # bounce
  - 1. # net
  - 1.  # empty
  learning_rate: 1.0e-03
  reset_optimizer: false
  loss:
    class_path: loss.MyCrossEntropyLoss
    init_args:
      class_weight: ${model.class_weight}
  acc:
    class_path: metric.NormalAccuracy
  relaxed_acc:
    class_path: metric.RelaxedAccuracy
  pce:
    class_path: metric.PCE
    init_args:
      threshold: 0.5
  smooth_pce:
    class_path: metric.SmoothPCE
    init_args:
      ev_diff_thresh: 0.25
        
data:
<<<<<<< HEAD
  # train_path: 'data_resplit/exclude_minus_1_train_event_new_9_exp80_center_net_add_pos_pred_weight_add_no_ball_frame_3_frames_full.pkl'
  # val_path: 'data_resplit/exclude_minus_1_val_event_new_9_exp80_center_net_add_pos_pred_weight_add_no_ball_frame_3_frames_full.pkl'
  # test_path: 'data_resplit/exclude_minus_1_test_event_new_9_exp80_center_net_add_pos_pred_weight_add_no_ball_frame_3_frames_full.pkl'
  # predict_path: 'data_resplit/exclude_minus_1_test_event_new_9_exp80_center_net_add_pos_pred_weight_add_no_ball_frame_3_frames_full.pkl'
=======
  # train_path: 'data/train_event_new_9.pkl'
  # val_path: 'data/val_event_new_9.pkl'
  # test_path: 'data/test_event_new_9.pkl'
  # predict_path: 'data/test_event_new_9.pkl'

  train_path: 'data/yolo_train_event_new_9.pkl'
  val_path: 'data/yolo_val_event_new_9.pkl'
  test_path: 'data/yolo_test_event_new_9.pkl'
  predict_path: 'data/yolo_test_event_new_9.pkl'

>>>>>>> 7fd1f88b4441a7f09042f083ac38c4004f7835c1

  # train_path: data_resplit/event_train_dict_9_yolo_1280.pkl
  # val_path: data_resplit/event_val_dict_9_yolo_1280.pkl
  # test_path: data_resplit/event_test_dict_9_yolo_1280.pkl
  # predict_path: data_resplit/event_test_dict_9_yolo_1280.pkl

  # train_path: 'data_resplit/exclude_minus_1_train_val_event_new_9_exp80_center_net_add_pos_pred_weight_add_no_ball_frame_3_frames_full.pkl'
  # val_path: 'data_resplit/exclude_minus_1_test_event_new_9_exp80_center_net_add_pos_pred_weight_add_no_ball_frame_3_frames_full.pkl'
  # test_path: 'data_resplit/exclude_minus_1_test_event_new_9_exp80_center_net_add_pos_pred_weight_add_no_ball_frame_3_frames_full.pkl'
  # predict_path: 'data_resplit/exclude_minus_1_test_event_new_9_exp80_center_net_add_pos_pred_weight_add_no_ball_frame_3_frames_full.pkl'

  train_path: data_resplit/train_event_new_9_exp90_centernet_no_asl_640.pkl
  val_path: data_resplit/val_event_new_9_exp90_centernet_no_asl_640.pkl
  test_path: data_resplit/test_event_new_9_exp90_centernet_no_asl_640.pkl
  predict_path: data_resplit/test_event_new_9_exp90_centernet_no_asl_640.pkl

  data_cfg: 
    n_input_frames: 9
    n_sample_limit: 1.0e+09
    crop_size:
    # - 360
    # - 150
    - 320
    - 128

    input_size:
    # - 256
    # - 182
    - 182
    - 182
<<<<<<< HEAD

    mask_red_ball: true
    ball_radius: 12  # on original 1920 x 1080 image
    thickness: -1
    tab_xmax_offset: 0
=======
    mask_red_ball: false
    ball_radius: 8
>>>>>>> 7fd1f88b4441a7f09042f083ac38c4004f7835c1
    do_augment: true
    already_cropped: false
    augment_props:
      augment_img_prob: 0.35
      mask_ball_prob: 0.15
      max_mask_ball: 4

  training_cfg:
    bs: 32
    shuffle_train: true
    num_workers: 8

ckpt_path: null